FROM alpine:latest@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b AS blocks

COPY samples/static/grafana-pyroscope-sample-blocks-public.zip /

RUN unzip grafana-pyroscope-sample-blocks-public.zip \
 && mv grafana-pyroscope-sample-blocks-public data-shared \
 && rm grafana-pyroscope-sample-blocks-public.zip

FROM docker.io/grafana/pyroscope:1.21.1@sha256:23f366803b418ca6b80f510f2dbcec22178a836dfe1fe828261d93273c0a4f97

COPY samples/static/pyroscope/config.yaml /etc/pyroscope/config.yaml
COPY --from=blocks --chown=pyroscope:pyroscope data-shared /data-shared

ENTRYPOINT ["/usr/bin/pyroscope"]
CMD ["-config.file=/etc/pyroscope/config.yaml"]
